[phases.setup]
nixPkgs = ["python311", "gcc", "gnumake"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -U pip", "pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
