[phases.setup]
nixPkgs = ["python311", "gcc", "gnumake"]

[phases.install]
cmds = [
    "python -m venv .venv",
    ".venv/bin/pip install -U pip",
    ".venv/bin/pip install -r requirements.txt"
]

[start]
cmd = ".venv/bin/uvicorn main:app --host 0.0.0.0 --port $PORT"
